### ISSUE TITLE
Syncthing on FreeBSD 11.0 freezes machine

### ISSUE THREAD

**Issue by kapfenho** [syncthing/syncthing#3733]
Starting syncthing on one of my FreeBSD server freezes machine, while syncthing 
runs without problems on other FreeBSD machines. During freeze, console and network 
connections block, no log messages are written, no dumps are produced. Freeze happens 
right after program start, every time.

I've tried to switch off local announcements: no change.
Running under unpriv user, running inside jail, running with nice set: no change.

No freeze happens while running syncthing under truss.

--- snip ---
[monitor] 08:47:09 INFO: Starting syncthing
[P6QWS] 08:47:09 INFO: syncthing v0.14.7 "Dysprosium Dragonfly" (go1.7.3 freebsd-amd64) nobody@packages.vie.agoracon.at 2016-11-10 02:29:05 UTC
[P6QWS] 08:47:09 INFO: My ID: P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS
[P6QWS] 08:47:09 INFO: Single thread hash performance is ~173 MB/s
[P6QWS] 08:47:09 INFO: Ready to synchronize urtuv-95pke (readwrite)
[P6QWS] 08:47:09 INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[P6QWS] 08:47:09 INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[P6QWS] 08:47:09 INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[P6QWS] 08:47:09 INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[P6QWS] 08:47:09 INFO: TCP listener (10.80.1.6:22000) starting
[P6QWS] 08:47:09 INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[P6QWS] 08:47:09 INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[P6QWS] 08:47:09 INFO: Completed initial scan (rw) of folder urtuv-95pke
[P6QWS] 08:47:09 INFO: Device P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS is "vilma.vie.agoracon.at" at [tcp4://10.80.1.6:22000]
[P6QWS] 08:47:09 INFO: GUI and API listening on 127.0.0.1:8384
[P6QWS] 08:47:09 INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
--- snap ---

### Version Information

Syncthing Version: v0.14.7
OS Version: FreeBSD 11.0-STABLE
Filesystem: ZFS
Machine: 128 GB RAM, Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz

**Comment by AudriusButkevicius** [comment]
No software should be able to freeze the OS/hardware. I suggest you look for an explanation elsewhere.

**Comment by calmh** [comment]
Yeah, not sure what we can do here. Need to get a crash dump or something out of FreeBSD, then if there's a specific thing we're doing it to cause it maybe we can workaround that once we know what it is. But in the end it sound like a FreeBSD problem.

**Comment by kapfenho** [comment]
Hi Jakob,

I've prepared some information related to this very strange "machine
freeze" on one of my FreeBSD machines.

This is not to blame someone (but me) - only to understand this problem
better.  I think the symptoms are OS related, the original problem maybe
not.  For me the problem is solved, but others may still run into it...

Syncthing runs fine on all FreeBSD machines but one, which is a
production server where analysis work is limited.

The problem is triggered by the NAT setting

        <natEnabled>true</natEnabled>

The machine has several public IP addresses configured (vlan100) based
on a bonding interface (lagg0).

You would not use NAT in this situation, but the generated default has
this setting switched on.

I can't say in what situation the machine gets when this is setting is
switched on - I have never seen this before on any OS.

Sorry for not being more specific on my inital bug report.

Cheers,
Horst

Below you find:

- network config
- one run (app trace mode) w/o nat -> no problem
- one run (app trace mode) w nat   -> problem


# network interfaces

+--------+
|        |
|  em0   +----+
|        |    |     +---------+
+--------+    |     |         |    [ bonding ]
              +-----+  lagg0  |    10.80.1.6/24
+--------+    |     |         |
|        |    |     +----+----+
|  em1   +----+          |  
|        |               |  +---------
+--------+               |  |            public IPv4:
                         +--+  vlan100   x.x.x.x1/y
                            |            x.x.x.x2/y
                            +---------



em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
        ether 0c:c4:7a:01:4d:2a
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
em1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
        ether 0c:c4:7a:01:4d:2a
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3
        inet 127.0.0.1 netmask 0xff000000
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        groups: lo
lagg0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=4219b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,TSO4,WOL_MAGIC,VLAN_HWTSO>
        ether 0c:c4:7a:01:4d:2a
        inet 10.80.1.6 netmask 0xffffff00 broadcast 10.80.1.255
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: active
        groups: lagg
        laggproto loadbalance lagghash l2,l3,l4
        laggport: em0 flags=4<ACTIVE>
        laggport: em1 flags=4<ACTIVE>
vlan100: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=103<RXCSUM,TXCSUM,TSO4>
        ether 0c:c4:7a:01:4d:2a
        inet x.x.x.x netmask 0xfffffff0 broadcast x.x.x.x
        inet x.x.x.x netmask 0xfffffff0 broadcast x.x.x.x
        inet x.x.x.x netmask 0xfffffff0 broadcast x.x.x.x
        inet x.x.x.x netmask 0xfffffff0 broadcast x.x.x.x
        inet x.x.x.x netmask 0xfffffff0 broadcast x.x.x.x
        inet x.x.x.x netmask 0xfffffff0 broadcast x.x.x.x
        nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
        media: Ethernet autoselect
        status: active
        vlan: 100 vlanpcp: 0 parent interface: lagg0
        groups: vlan


##########################################################################################
# NAT disabled: no problem

<configuration version="16">
    <device id="P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS" name="vilma.vie.agoracon.at" compression="metadata" introducer="false">
        <address>tcp4://10.80.1.6:22000</address>
    </device>
    <gui enabled="true" tls="false" debugging="false">
        <address>127.0.0.1:8384</address>
        <apikey>44JJ76cigKTAkzUdZcgFfXXuHswpdpfj</apikey>
        <theme>default</theme>
    </gui>
    <options>
        <listenAddress>tcp4://10.80.1.6:22000</listenAddress>
        <globalAnnounceServer>default</globalAnnounceServer>
        <globalAnnounceEnabled>true</globalAnnounceEnabled>
        <localAnnounceEnabled>false</localAnnounceEnabled>
        <localAnnouncePort>21027</localAnnouncePort>
        <localAnnounceMCAddr>[ff12::8384]:21027</localAnnounceMCAddr>
        <maxSendKbps>0</maxSendKbps>
        <maxRecvKbps>0</maxRecvKbps>
        <reconnectionIntervalS>60</reconnectionIntervalS>
        <relaysEnabled>true</relaysEnabled>
        <relayReconnectIntervalM>10</relayReconnectIntervalM>
        <startBrowser>false</startBrowser>
        <natEnabled>false</natEnabled>
        <natLeaseMinutes>60</natLeaseMinutes>
        <natRenewalMinutes>30</natRenewalMinutes>
        <natTimeoutSeconds>10</natTimeoutSeconds>
        <urAccepted>0</urAccepted>
        <urUniqueID></urUniqueID>
        <urURL>https://data.syncthing.net/newdata</urURL>
        <urPostInsecurely>false</urPostInsecurely>
        <urInitialDelayS>1800</urInitialDelayS>
        <restartOnWakeup>true</restartOnWakeup>
        <autoUpgradeIntervalH>12</autoUpgradeIntervalH>
        <keepTemporariesH>24</keepTemporariesH>
        <cacheIgnoredFiles>false</cacheIgnoredFiles>
        <progressUpdateIntervalS>5</progressUpdateIntervalS>
        <symlinksEnabled>true</symlinksEnabled>
        <limitBandwidthInLan>false</limitBandwidthInLan>
        <minHomeDiskFreePct>1</minHomeDiskFreePct>
        <releasesURL>https://upgrades.syncthing.net/meta.json</releasesURL>
        <overwriteRemoteDeviceNamesOnConnect>false</overwriteRemoteDeviceNamesOnConnect>
        <tempIndexMinBlocks>10</tempIndexMinBlocks>
    </options>
</configuration>



export STTRACE="beacon,config,connections,db,dialer,discover,events,http,main,model,nat,pmp,protocol,scanner,stats,sync,upgrade,upnp,versioner"
# export GOMAXPROCS=1
export STPERFSTATS=true

syncthing -no-restart -no-browser -logfile="-" -verbose


11:15:47 DEBUG: Enabling lock logging at 100ms threshold
[start] 2016/11/18 11:15:47.349343 events.go:181: DEBUG: subscribe Unknown
[start] 2016/11/18 11:15:47.349419 events.go:181: DEBUG: subscribe Unknown
[start] 2016/11/18 11:15:47.349661 events.go:235: DEBUG: poll 1m0s
[P6QWS] 2016/11/18 11:15:47.359622 main.go:568: INFO: syncthing v0.14.7 "Dysprosium Dragonfly" (go1.7.3 freebsd-amd64) nobody@packages.vie.agoracon.at 2016-11-10 02:29:05 UTC
[P6QWS] 2016/11/18 11:15:47.359718 main.go:569: INFO: My ID: P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS
[P6QWS] 2016/11/18 11:15:47.665149 main.go:856: INFO: Single thread hash performance is ~173 MB/s
[P6QWS] 2016/11/18 11:15:47.665258 events.go:154: DEBUG: log 0 Starting map[home:/home/horst/.config/syncthing myID:P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS]
[P6QWS] 2016/11/18 11:15:47.665345 events.go:235: DEBUG: poll 1m0s
[P6QWS] 2016/11/18 11:15:47.665422 verboseservice.go:48: VERBOSE: Starting up (/home/horst/.config/syncthing)
[P6QWS] 2016/11/18 11:15:47.837920 progressemitter.go:197: DEBUG: progress emitter: updated interval 5s
[P6QWS] 2016/11/18 11:15:47.838080 service.go:415: DEBUG: Starting listener tcp4://10.80.1.6:22000
[P6QWS] 2016/11/18 11:15:47.838138 main.go:710: INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[P6QWS] 2016/11/18 11:15:47.838199 service.go:291: DEBUG: Reconnect loop
[P6QWS] 2016/11/18 11:15:47.838231 tcp_listen.go:69: INFO: TCP listener (10.80.1.6:22000) starting
[P6QWS] 2016/11/18 11:15:47.838247 main.go:710: INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[P6QWS] 2016/11/18 11:15:47.838291 service.go:385: DEBUG: initial rampup; sleep 1s and update to 2s
[P6QWS] 2016/11/18 11:15:47.838319 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:15:47.838336 main.go:710: INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[P6QWS] 2016/11/18 11:15:47.838363 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:15:47.838420 main.go:710: INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[P6QWS] 2016/11/18 11:15:47.838441 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:15:47.838475 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:15:47.838494 main.go:710: INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[P6QWS] 2016/11/18 11:15:47.838547 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:15:47.838565 main.go:710: INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[P6QWS] 2016/11/18 11:15:47.838599 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:15:47.838621 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:15:47.838679 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:15:47.838725 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:15:47.838754 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:15:47.838794 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:15:47.838845 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:15:47.840407 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 0
[P6QWS] 2016/11/18 11:15:47.840432 progressemitter.go:82: DEBUG: progress emitter: nothing new
[P6QWS] 2016/11/18 11:15:47.840553 global.go:224: DEBUG: announce POST: Post https://discovery-v6-2.syncthing.net/v2/: dial tcp [2604:a880:800:10::182:a001]:443: connect: no route to host
[P6QWS] 2016/11/18 11:15:47.840600 global.go:224: DEBUG: announce POST: Post https://discovery-v6-3.syncthing.net/v2/: dial tcp [2400:6180:0:d0::d9:d001]:443: connect: no route to host
[P6QWS] 2016/11/18 11:15:47.840635 global.go:224: DEBUG: announce POST: Post https://discovery-v6-4.syncthing.net/v2/: dial tcp [2a03:b0c0:0:1010::4ed:3001]:443: connect: no route to host
[P6QWS] 2016/11/18 11:15:47.849540 internal.go:51: DEBUG: Dialer logging disabled, as no proxy was detected
[P6QWS] 2016/11/18 11:15:47.864958 main.go:755: INFO: Device P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS is "vilma.vie.agoracon.at" at [tcp4://10.80.1.6:22000]
[P6QWS] 2016/11/18 11:15:47.865065 events.go:181: DEBUG: subscribe DeviceConnected
[P6QWS] 2016/11/18 11:15:47.865110 events.go:211: DEBUG: unsubscribe
[P6QWS] 2016/11/18 11:15:47.865135 events.go:154: DEBUG: log 1 StartupComplete map[myID:P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS]
[P6QWS] 2016/11/18 11:15:47.865176 verboseservice.go:48: VERBOSE: Startup complete
[P6QWS] 2016/11/18 11:15:47.865198 events.go:235: DEBUG: poll 1m0s
[P6QWS] 2016/11/18 11:15:47.866127 gui.go:332: INFO: GUI and API listening on 127.0.0.1:8384
[P6QWS] 2016/11/18 11:15:47.866150 gui.go:333: INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[P6QWS] 2016/11/18 11:15:47.866191 events.go:181: DEBUG: subscribe Unknown
[P6QWS] 2016/11/18 11:15:48.102299 global.go:229: DEBUG: announce POST: 204 No Content
[P6QWS] 2016/11/18 11:15:48.102322 global.go:256: DEBUG: announce Reannounce-After: 1800 <nil>
[P6QWS] 2016/11/18 11:15:48.365313 global.go:229: DEBUG: announce POST: 204 No Content
[P6QWS] 2016/11/18 11:15:48.365335 global.go:256: DEBUG: announce Reannounce-After: 1800 <nil>
[P6QWS] 2016/11/18 11:15:48.868218 service.go:291: DEBUG: Reconnect loop
[P6QWS] 2016/11/18 11:15:48.868247 service.go:385: DEBUG: initial rampup; sleep 2s and update to 4s
[P6QWS] 2016/11/18 11:15:49.352339 global.go:229: DEBUG: announce POST: 204 No Content
[P6QWS] 2016/11/18 11:15:49.352369 global.go:256: DEBUG: announce Reannounce-After: 1800 <nil>
[P6QWS] 2016/11/18 11:15:50.900093 service.go:291: DEBUG: Reconnect loop
[P6QWS] 2016/11/18 11:15:50.900121 service.go:385: DEBUG: initial rampup; sleep 4s and update to 8s
[P6QWS] 2016/11/18 11:15:54.935473 service.go:291: DEBUG: Reconnect loop
[P6QWS] 2016/11/18 11:15:54.935502 service.go:385: DEBUG: initial rampup; sleep 8s and update to 16s
[P6QWS] 2016/11/18 11:16:02.972987 service.go:291: DEBUG: Reconnect loop
[P6QWS] 2016/11/18 11:16:02.973023 service.go:385: DEBUG: initial rampup; sleep 16s and update to 32s
^C[P6QWS] 2016/11/18 11:16:02.974243 gui.go:351: DEBUG: shutting down (stop)
[P6QWS] 2016/11/18 11:16:02.974276 main.go:803: INFO: Exiting


##########################################################################################
# NAT enabled: machine freezes

<configuration version="16">
    <device id="P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS" name="vilma.vie.agoracon.at" compression="metadata" introducer="false">
        <address>tcp4://10.80.1.6:22000</address>
    </device>
    <gui enabled="true" tls="false" debugging="false">
        <address>127.0.0.1:8384</address>
        <apikey>44JJ76cigKTAkzUdZcgFfXXuHswpdpfj</apikey>
        <theme>default</theme>
    </gui>
    <options>
        <listenAddress>tcp4://10.80.1.6:22000</listenAddress>
        <globalAnnounceServer>default</globalAnnounceServer>
        <globalAnnounceEnabled>true</globalAnnounceEnabled>
        <localAnnounceEnabled>false</localAnnounceEnabled>
        <localAnnouncePort>21027</localAnnouncePort>
        <localAnnounceMCAddr>[ff12::8384]:21027</localAnnounceMCAddr>
        <maxSendKbps>0</maxSendKbps>
        <maxRecvKbps>0</maxRecvKbps>
        <reconnectionIntervalS>60</reconnectionIntervalS>
        <relaysEnabled>true</relaysEnabled>
        <relayReconnectIntervalM>10</relayReconnectIntervalM>
        <startBrowser>false</startBrowser>
        <natEnabled>true</natEnabled>
        <natLeaseMinutes>60</natLeaseMinutes>
        <natRenewalMinutes>30</natRenewalMinutes>
        <natTimeoutSeconds>10</natTimeoutSeconds>
        <urAccepted>0</urAccepted>
        <urUniqueID></urUniqueID>
        <urURL>https://data.syncthing.net/newdata</urURL>
        <urPostInsecurely>false</urPostInsecurely>
        <urInitialDelayS>1800</urInitialDelayS>
        <restartOnWakeup>true</restartOnWakeup>
        <autoUpgradeIntervalH>12</autoUpgradeIntervalH>
        <keepTemporariesH>24</keepTemporariesH>
        <cacheIgnoredFiles>false</cacheIgnoredFiles>
        <progressUpdateIntervalS>5</progressUpdateIntervalS>
        <symlinksEnabled>true</symlinksEnabled>
        <limitBandwidthInLan>false</limitBandwidthInLan>
        <minHomeDiskFreePct>1</minHomeDiskFreePct>
        <releasesURL>https://upgrades.syncthing.net/meta.json</releasesURL>
        <overwriteRemoteDeviceNamesOnConnect>false</overwriteRemoteDeviceNamesOnConnect>
        <tempIndexMinBlocks>10</tempIndexMinBlocks>
    </options>
</configuration>


export STTRACE="beacon,config,connections,db,dialer,discover,events,http,main,model,nat,pmp,protocol,scanner,stats,sync,upgrade,upnp,versioner"
# export GOMAXPROCS=1
export STPERFSTATS=true

syncthing -no-restart -no-browser -logfile="-" -verbose


11:17:24 DEBUG: Enabling lock logging at 100ms threshold
[start] 2016/11/18 11:17:24.076791 events.go:181: DEBUG: subscribe Unknown
[start] 2016/11/18 11:17:24.076941 events.go:181: DEBUG: subscribe Unknown
[start] 2016/11/18 11:17:24.077004 events.go:235: DEBUG: poll 1m0s
[P6QWS] 2016/11/18 11:17:24.087047 main.go:568: INFO: syncthing v0.14.7 "Dysprosium Dragonfly" (go1.7.3 freebsd-amd64) nobody@packages.vie.agoracon.at 2016-11-10 02:29:05 UTC
[P6QWS] 2016/11/18 11:17:24.087144 main.go:569: INFO: My ID: P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS
[P6QWS] 2016/11/18 11:17:24.392720 main.go:856: INFO: Single thread hash performance is ~173 MB/s
[P6QWS] 2016/11/18 11:17:24.392852 events.go:154: DEBUG: log 0 Starting map[home:/home/horst/.config/syncthing myID:P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS]
[P6QWS] 2016/11/18 11:17:24.392940 events.go:235: DEBUG: poll 1m0s
[P6QWS] 2016/11/18 11:17:24.393003 verboseservice.go:48: VERBOSE: Starting up (/home/horst/.config/syncthing)
[P6QWS] 2016/11/18 11:17:24.396794 progressemitter.go:197: DEBUG: progress emitter: updated interval 5s
[P6QWS] 2016/11/18 11:17:24.396930 service.go:415: DEBUG: Starting listener tcp4://10.80.1.6:22000
[P6QWS] 2016/11/18 11:17:24.396953 service.go:492: DEBUG: Starting NAT service
[P6QWS] 2016/11/18 11:17:24.397114 main.go:710: INFO: Using discovery server https://discovery-v4-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[P6QWS] 2016/11/18 11:17:24.397176 service.go:291: DEBUG: Reconnect loop
[P6QWS] 2016/11/18 11:17:24.397200 service.go:385: DEBUG: initial rampup; sleep 1s and update to 2s
[P6QWS] 2016/11/18 11:17:24.397225 main.go:710: INFO: Using discovery server https://discovery-v4-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[P6QWS] 2016/11/18 11:17:24.397260 tcp_listen.go:69: INFO: TCP listener (10.80.1.6:22000) starting
[P6QWS] 2016/11/18 11:17:24.397322 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:17:24.397368 main.go:710: INFO: Using discovery server https://discovery-v4-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[P6QWS] 2016/11/18 11:17:24.397407 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:17:24.397440 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:17:24.397471 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:17:24.397484 main.go:710: INFO: Using discovery server https://discovery-v6-2.syncthing.net/v2/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC
[P6QWS] 2016/11/18 11:17:24.397519 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:17:24.397559 main.go:710: INFO: Using discovery server https://discovery-v6-3.syncthing.net/v2/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
[P6QWS] 2016/11/18 11:17:24.397588 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:17:24.397630 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:17:24.397649 main.go:710: INFO: Using discovery server https://discovery-v6-4.syncthing.net/v2/?id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
[P6QWS] 2016/11/18 11:17:24.397692 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:17:24.397729 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:17:24.397761 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:17:24.397791 events.go:181: DEBUG: subscribe ListenAddressesChanged
[P6QWS] 2016/11/18 11:17:24.397816 global.go:220: DEBUG: Announcement: {"addresses":["tcp4://10.80.1.6:22000"]}
[P6QWS] 2016/11/18 11:17:24.399402 progressemitter.go:63: DEBUG: progress emitter: timer - looking after 0
[P6QWS] 2016/11/18 11:17:24.399423 progressemitter.go:82: DEBUG: progress emitter: nothing new
[P6QWS] 2016/11/18 11:17:24.399890 global.go:224: DEBUG: announce POST: Post https://discovery-v6-2.syncthing.net/v2/: dial tcp [2604:a880:800:10::182:a001]:443: connect: no route to host
[P6QWS] 2016/11/18 11:17:24.400019 global.go:224: DEBUG: announce POST: Post https://discovery-v6-3.syncthing.net/v2/: dial tcp [2400:6180:0:d0::d9:d001]:443: connect: no route to host
[P6QWS] 2016/11/18 11:17:24.400216 global.go:224: DEBUG: announce POST: Post https://discovery-v6-4.syncthing.net/v2/: dial tcp [2a03:b0c0:0:1010::4ed:3001]:443: connect: no route to host
[P6QWS] 2016/11/18 11:17:24.423891 main.go:755: INFO: Device P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS is "vilma.vie.agoracon.at" at [tcp4://10.80.1.6:22000]
[P6QWS] 2016/11/18 11:17:24.423996 events.go:181: DEBUG: subscribe DeviceConnected
[P6QWS] 2016/11/18 11:17:24.424051 events.go:211: DEBUG: unsubscribe
[P6QWS] 2016/11/18 11:17:24.424076 events.go:154: DEBUG: log 1 StartupComplete map[myID:P6QWSRW-IRMF245-PBFEWDR-XTPC6GQ-ZUW3CXI-QFXFTNK-ZVBK5ZI-ZCU2SAS]
[P6QWS] 2016/11/18 11:17:24.424120 verboseservice.go:48: VERBOSE: Startup complete
[P6QWS] 2016/11/18 11:17:24.424143 events.go:235: DEBUG: poll 1m0s
[P6QWS] 2016/11/18 11:17:24.425017 gui.go:332: INFO: GUI and API listening on 127.0.0.1:8384
[P6QWS] 2016/11/18 11:17:24.425040 gui.go:333: INFO: Access the GUI via the following URL: http://127.0.0.1:8384/
[P6QWS] 2016/11/18 11:17:24.425067 events.go:181: DEBUG: subscribe Unknown
[P6QWS] 2016/11/18 11:17:24.585950 internal.go:51: DEBUG: Dialer logging disabled, as no proxy was detected
[P6QWS] 2016/11/18 11:17:24.612751 global.go:229: DEBUG: announce POST: 204 No Content
[P6QWS] 2016/11/18 11:17:24.612776 global.go:256: DEBUG: announce Reannounce-After: 1800 <nil>
[P6QWS] 2016/11/18 11:17:24.872823 global.go:229: DEBUG: announce POST: 204 No Content
[P6QWS] 2016/11/18 11:17:24.872845 global.go:256: DEBUG: announce Reannounce-After: 1800 <nil>
[P6QWS] 2016/11/18 11:17:25.416647 service.go:291: DEBUG: Reconnect loop
[P6QWS] 2016/11/18 11:17:25.416677 service.go:385: DEBUG: initial rampup; sleep 2s and update to 4s
[P6QWS] 2016/11/18 11:17:25.416928 upnp.go:150: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on em0
[P6QWS] 2016/11/18 11:17:25.416955 upnp.go:150: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on lo0
[P6QWS] 2016/11/18 11:17:25.416992 upnp.go:150: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on em1
[P6QWS] 2016/11/18 11:17:25.417035 upnp.go:150: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on em0
[P6QWS] 2016/11/18 11:17:25.417072 upnp.go:150: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on lagg0
[P6QWS] 2016/11/18 11:17:25.417095 upnp.go:150: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:2 on vlan100
[P6QWS] 2016/11/18 11:17:25.418363 upnp.go:150: DEBUG: Starting discovery of device type urn:schemas-upnp-org:device:InternetGatewayDevice:1 on vlan100
[P6QWS] 2016/11/18 11:17:25.418554 upnp.go:154: DEBUG: listen udp4 239.255.255.250:0: setsockopt: no such network interface
[P6QWS] 2016/11/18 11:17:25.418620 upnp.go:154: DEBUG: listen udp4 239.255.255.250:0: setsockopt: no such network interface

--> machine stops to react here, no network connections, console dead, no dump triggered (or my dump devide is broken)




On 14. Nov 2016, at 12:05, Jakob Borg <notifications@github.com> wrote:

Yeah, not sure what we can do here. Need to get a crash dump or something out of FreeBSD, then if there's a specific thing we're doing it to cause it maybe we can workaround that once we know what it is. But in the end it sound like a FreeBSD problem.

**Comment by AudriusButkevicius** [comment]
Sounds like a bug in the kernel, we just send a broadcast/multicast to every interface, which shouldn't kill your machine.

**Comment by calmh** [comment]
The NAT support does discovery by multcast, much like the local discovery that used to crash FreeBSD left and right. Sounds like they may still not have gotten multicast right for all types of interfaces.

**Comment by DimitryAndric** [comment]
FWIW, I have been running syncthing since quite some time on FreeBSD 11-STABLE (currently at r309548), and never experienced any problems.  `natEnabled` is set to `true` in `config.xml` too.  Currently at syncthing v0.14.15, built with go 1.7.3 for freebsd-amd64.

@kapfenho, are you using NAT on the FreeBSD host itself?  And if so, is this using pf or ipnat?
