### ISSUE TITLE
panic: proto: wrong wireType = 1 for field Type

### ISSUE THREAD

**Issue by Kezxo** [syncthing/syncthing#3881]
I just noticed that my syncthing had been offline since 27th dec so checked to see what's up and it said "Panic detected" when I tried to run it. 
I got panic logs from both  v0.14.17 and  v0.14.18, I upgraded syncthing not knowing about this issue. This is the latest panic log:

```
[FQ3PV] 15:02:08 INFO: syncthing v0.14.18 "Dysprosium Dragonfly" (go1.8beta2 linux-amd64) jenkins@build.syncthing.net 2017-01-01 17:19:00 UTC
[FQ3PV] 15:02:08 INFO: My ID: ASDF
[FQ3PV] 15:02:09 INFO: Single thread hash performance is 183 MB/s using minio/sha256-simd (145 MB/s using crypto/sha256).
[FQ3PV] 15:02:09 INFO: Ready to synchronize "Device name" (Device-ID) (readwrite)
...
Panic at 2017-01-06T15:02:09+01:00
panic: proto: wrong wireType = 1 for field Type

goroutine 1 [running]:
github.com/syncthing/syncthing/lib/db.getFile(0xfa8740, 0xc420341940, 0xc420678580, 0x34, 0x34, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb.go:78 +0x210
github.com/syncthing/syncthing/lib/db.readOnlyTransaction.getFile(0xc4202584e0, 0xc420168450, 0xc420405710, 0xb, 0x10, 0xc420318da0, 0x20, 0x20, 0xc42017a805, 0x2b, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:39 +0x175
github.com/syncthing/syncthing/lib/db.(*Instance).checkGlobals(0xc420168450, 0xc420405710, 0xb, 0x10, 0xc420242878)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:605 +0x5f4
github.com/syncthing/syncthing/lib/db.NewFileSet(0xc42012f734, 0xb, 0xc420168450, 0xc42022a690)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/db/set.go:125 +0x225
github.com/syncthing/syncthing/lib/model.(*Model).addFolderLocked(0xc42008c140, 0xc42012f734, 0xb, 0xc42012f760, 0xd, 0xc4200e5e20, 0x1a, 0x0, 0xc42017a380, 0x2, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:315 +0x104
github.com/syncthing/syncthing/lib/model.(*Model).AddFolder(0xc42008c140, 0xc42012f734, 0xb, 0xc42012f760, 0xd, 0xc4200e5e20, 0x1a, 0x0, 0xc42017a380, 0x2, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:309 +0xa1
main.syncthingMain(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb076c4, 0x1, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:724 +0x28f6
main.main()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:380 +0x283

goroutine 9 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc420094f00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:90 +0x5d9
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:139 +0x581

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 17 [chan receive]:
main.trackCPUUsage()
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:24 +0x103
created by main.init.3
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/gui_unix.go:17 +0x35

goroutine 18 [select, locked to thread]:
runtime.gopark(0xc9f530, 0x0, 0xb0a5ae, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:261 +0x13a
runtime.selectgoImpl(0xc4201cef50, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x1308
runtime.selectgo(0xc4201cef50)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2184 +0x1

goroutine 19 [chan receive]:
main.setupSignalHandling.func1(0xc42017c420)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:860 +0x40
created by main.setupSignalHandling
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:862 +0xbc

goroutine 20 [chan receive]:
main.setupSignalHandling.func2(0xc42017c5a0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:870 +0x40
created by main.setupSignalHandling
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/cmd/syncthing/main.go:872 +0x181

goroutine 21 [select]:
github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).Serve(0xc4201b00e0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:338 +0xf65
created by github.com/syncthing/syncthing/vendor/github.com/thejerf/suture.(*Supervisor).ServeBackground
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/thejerf/suture/supervisor.go:297 +0x43

goroutine 22 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc42016a400, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:248 +0x3ee
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420166410)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:302 +0x5f
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:296 +0x1a3

goroutine 23 [select]:
github.com/syncthing/syncthing/lib/events.(*Subscription).Poll(0xc42016a460, 0xdf8475800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:248 +0x3ee
github.com/syncthing/syncthing/lib/events.(*bufferedSubscription).pollingLoop(0xc420166460)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:302 +0x5f
created by github.com/syncthing/syncthing/lib/events.NewBufferedSubscription
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/events/events.go:296 +0x1a3

goroutine 33 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).drain(0xc4201b0000)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:206 +0x23f
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/util/buffer_pool.go:237 +0x19a

goroutine 10 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mpoolDrain(0xc420094f00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_state.go:96 +0x249
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:140 +0x5a3

goroutine 11 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).tCompaction(0xc420094f00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:804 +0x638
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:146 +0x720

goroutine 12 [select]:
github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.(*DB).mCompaction(0xc420094f00)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:751 +0x242
created by github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb.openDB
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/vendor/github.com/syndtr/goleveldb/leveldb/db.go:147 +0x742

goroutine 13 [select]:
github.com/syncthing/syncthing/lib/model.(*ProgressEmitter).Serve(0xc420054be0)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/progressemitter.go:56 +0x559
created by github.com/syncthing/syncthing/lib/model.NewModel
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/model/model.go:166 +0x99a

goroutine 14 [chan receive]:
github.com/syncthing/syncthing/lib/versioner.NewStaggered.func1(0xc420258420, 0x24, 0xe10, 0xc4200e5de0, 0x19, 0x1e, 0xe10, 0xe10, 0x15180, 0x15180, ...)
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/versioner/staggered.go:83 +0x114
created by github.com/syncthing/syncthing/lib/versioner.NewStaggered
	/home/buildslave/workspace/syncthing-release/src/github.com/syncthing/syncthing/lib/versioner/staggered.go:86 +0x47c
```

### Version Information

Syncthing Version: v0.14.17 and v0.14.18
OS Version: Ubuntu server 16.04.1 LTS

**Comment by canton7** [comment]
Looks similar to #3855, which was fixed in v0.14.18, released 5 days ago.

**Comment by AudriusButkevicius** [comment]
Upgrade all clients to the latest version.

**Comment by Kezxo** [comment]
I thought I was using the latest version, am I missing something here?

Den fre 6 jan. 2017 16:21Audrius Butkevicius <notifications@github.com>
skrev:

**Comment by AudriusButkevicius** [comment]
You posted yourself:

`Syncthing Version: v0.14.17 and v0.14.18`

**Comment by Kezxo** [comment]
Yes, it started in the last version and it keeps happening in the newest one. The log I posted is from v0.14.18.
Maybe I was unclear but I can't get syncthing to run and that panic log is all I get.
Maybe the last version broke something and the new version won't brake the same way but it's still broken for me here.

**Comment by AudriusButkevicius** [comment]
Actually its something else than I thought

**Comment by AudriusButkevicius** [comment]
You'd have to nuke your index directory and rescan from scratch

**Comment by Kezxo** [comment]
That did the trick! Thanks!

**Comment by calmh** [comment]
This one I don't get. In all the recent versions, the marshalling for both `FileInfo` and `FileInfoTruncated` does

```go
func (m *FileInfoTruncated) MarshalTo(data []byte) (int, error) {
...
	if m.Type != 0 {
		data[i] = 0x10
		i++
		i = encodeVarintStructs(data, i, uint64(m.Type))
	}
...
```

where `0x10` is `0b10000`, where the last three bits (`000`) is the wire type and `10` is the field number (2). There should never have been any marshalling with a `Type` field of type 1 ("fixed64").

**Comment by calmh** [comment]
I suspect random one-off corruption.
