### ISSUE TITLE
panic: bug: removed more than added

### ISSUE THREAD

**Issue by bugith** [syncthing/syncthing#4659]
On 0.14.43-rc1 Win10 64
This doen't seem the same than the recent #4652 #4605

[panic-20180109-144625.log](https://github.com/syncthing/syncthing/files/1615483/panic-20180109-144625.log)
(redacted log)
On the remote ubuntu64 0.14.42 side I have panics too, but with same error as the 2 above.
Another (WinXP32 tried with v42 & 43) doesn't show the panic, but is neither direct linked to this Win64, nor to the folder shared with the Win10 & the Ub42(and others)

**Comment by bugith** [comment]
More setup infos:
All sync is currently done
Folder share between : 
A : the friend's machine showing this bug
B : my Ubuntu14-64 0.14.42 desktop shows global 90 files, 1 folder, 3GB, connection to A blinks and when reconnect B synch's quickly to A up to 99% 128B
C : my laptop Ubuntu14-64 0.14.43-rc1 with 2 Ignore files for this folder (shows global 91 files, 1 folder ~5GB; local 88 files, 1 folder 400MB)
Both my 2 B & C devices are on the same LAN and show Uptodate to each other (although this strange 90/91). 
O : some other friends (only one online ATM being 14.43-rc1 (Win7-32 not sure))
A<->B<->C
A<->O
B<->O

**Comment by calmh** [comment]
```
Panic at 2018-01-09T14:46:25+01:00
panic: bug: removed more than added
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x975b46]

goroutine 1368 [running]:
github.com/syncthing/syncthing/lib/model.(*Model).Closed(0xc04219c480, 0x110f080, 0xc0420323c0, 0x0, 0x0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/model/model.go:1299 +0x486
github.com/syncthing/syncthing/lib/protocol.(*nativeModel).Closed(0xc043848f30, 0x110f080, 0xc0420323c0, 0x0, 0x0)
	<autogenerated>:1 +0x6b
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).close.func1()
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:778 +0x212
sync.(*Once).Do(0xc042032448, 0xc043d69178)
	C:/Go/src/sync/once.go:44 +0xc5
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).close(0xc0420323c0, 0x0, 0x0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:765 +0x72
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop.func1(0xc0420323c0, 0xc043d69fd0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:280 +0x48
panic(0xab32a0, 0xdd03b0)
	C:/Go/src/runtime/panic.go:491 +0x291
github.com/syncthing/syncthing/lib/db.(*metadataTracker).removeFile(0xc04286dec0, 0xf8f8f8f8f8f8f8f8, 0xf8f8f8f8f8f8f8f8, 0xf8f8f8f8f8f8f8f8, 0xf8f8f8f8f8f8f8f8, 0x110eb40, 0xc0441922d0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/db/meta.go:138 +0x4fe
github.com/syncthing/syncthing/lib/db.readWriteTransaction.removeFromGlobal(0xc0437715c0, 0xc04217e3f0, 0xc0440f0500, 0xc042e62790, 0xb, 0x10, 0xc0441e2da0, 0x20, 0x20, 0xc04200c349, ...)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/db/leveldb_transactions.go:223 +0x6f9
github.com/syncthing/syncthing/lib/db.(*Instance).dropDeviceFolder(0xc04217e3f0, 0xc0441e2da0, 0x20, 0x20, 0xc042e62790, 0xb, 0x10, 0xc04286dec0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/db/leveldb_dbinstance.go:476 +0x25a
github.com/syncthing/syncthing/lib/db.(*FileSet).Drop(0xc04207c460, 0xf740c6f0e1aecfbd, 0x3b420258b013bea7, 0x9307d02482a7372e, 0x1295383389660915)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/db/set.go:104 +0x258
github.com/syncthing/syncthing/lib/model.(*Model).Index(0xc04219c480, 0xf740c6f0e1aecfbd, 0x3b420258b013bea7, 0x9307d02482a7372e, 0x1295383389660915, 0xc042e62120, 0xb, 0xc044f3a000, 0x59, 0x8e)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/model/model.go:849 +0x487
github.com/syncthing/syncthing/lib/protocol.nativeModel.Index(0x133f110, 0xc04219c480, 0xf740c6f0e1aecfbd, 0x3b420258b013bea7, 0x9307d02482a7372e, 0x1295383389660915, 0xc042e62120, 0xb, 0xc044f3a000, 0x59, ...)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/protocol/nativemodel_windows.go:20 +0xbc
github.com/syncthing/syncthing/lib/protocol.(*nativeModel).Index(0xc043848f30, 0xf740c6f0e1aecfbd, 0x3b420258b013bea7, 0x9307d02482a7372e, 0x1295383389660915, 0xc042e62120, 0xb, 0xc044f3a000, 0x59, 0x8e)
	<autogenerated>:1 +0xb2
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).handleIndex(0xc0420323c0, 0xc042e62120, 0xb, 0xc044f3a000, 0x59, 0x8e)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:464 +0x1ca
github.com/syncthing/syncthing/lib/protocol.(*rawConnection).readerLoop(0xc0420323c0, 0x0, 0x0)
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:317 +0xd48
created by github.com/syncthing/syncthing/lib/protocol.(*rawConnection).Start
	C:/Temp/syncthing-d3d5715d/src/github.com/syncthing/syncthing/lib/protocol/protocol.go:171 +0x4a
```

Cool double panic, but root cause is probably something wrong with my persistent accounting stuff.

**Comment by bugith** [comment]
Cool ? Means easier to dig  ? Would you need the log from the 2nd panicking device ? It is
"...
[LF5AG] 13:15:23 INFO: Joined relay relay://79.137.32.223:22067
Panic at 2018-01-09T13:15:28+01:00
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8337bb]
..."

**Comment by AudriusButkevicius** [comment]
Yeah, posting which part panics would be nice.

**Comment by bugith** [comment]
I guess some bad fun to redact this one a coherent way :(
Maybe these are 2 different issues, but I'll post this 2nd log close in timestamp to the other
Ok, I work

**Comment by bugith** [comment]
Here is the cooking . On this Ub14-42, panicking ended on this logfile
[panic-20180109-131557.log](https://github.com/syncthing/syncthing/files/1616136/panic-20180109-131557.log)

**Comment by AudriusButkevicius** [comment]
This is fixed in the latest version. Also, we usually don't need the log prior the panic,so no point obfuscating things we don't need.

**Comment by bugith** [comment]
So it is advised to upgrade my ub14-42 to 14.43 quickly?
Good to know. This #4659 remains open because of the first log (the 14.43 Win10 machine)?

**Comment by AudriusButkevicius** [comment]
No. The two panics are unrelated, but one of them is fixed.

**Comment by bugith** [comment]
Now, one remote device removed 2 big files
B shows local+global 88/1/391MiB Up to date
C shows local 88/1/391MiB Up to date + global 89/1/2.50GiB, the delta being the size of one of the 2 removed files, which were both really removed everywhere in the shared-folder.

**Comment by bugith** [comment]
Update info
All nodes have now switch to v.0.14.43 and are set at autoupdate Stable, but C (43 +set rc autoupdate) and the folder initiator node which is one from the O friends (O1), is Ub Mate 17 or 18 x86 and is still non updated at 0.14.40 level (syncthing stable repo). This one didn't went up since B & C saw it on for the last time (I'm not sure O1-B link for the share is accepted at O1 side).
I fogot to say at the initiation time, C-O link for the share was R/W effective on both sides, and there is nor was Read only nodes in the cluster for the share. I removed C-O later.
Yesterday night, I removed the share on C then recreated it just like it was the minute before (single link to B).
C immediately became uptodate with B (same as B shows with C), global/local 88-1-391MiB/88-1-391MiB, and B now shows g/l 89-1-391/88-1-391MiB (I didn't say what local was on B on the beginning)... I'll update today when O1 is up I hope. Bye

**Comment by bugith** [comment]
BTW, B machine won't panic anymore since 42 upgraded to 43. now all machines in the cluster show global=local but B still showing global=local+1
A still panics

**Comment by AudriusButkevicius** [comment]
Is A the first panic you posted?

**Comment by bugith** [comment]
Yes it is, Audrius

**Comment by bugith** [comment]
About B global/local mismatch, this may probably be not related to the A panic, but instead to mismatch ignores in the cluster* as stated in ignores documentation and #623 + #624 . Sorry if that was confusing

* there are mostly windows involved in this folder share and I don't want these weird *.lnk | *.ini | *.db in my nuxes ;-) . Case sensitivity differences may be another reason. Not a real issue in itself.
I'm currently waiting for the friend's A machine new logs and config ....

**Comment by bugith** [comment]
New : 
A upgraded to 014.43 release
Still panic
started st with -pause .... => quiet, no panic :)
resumed all shares & devices one at a time, keep the presume culprit (B) for the end
all quiet and uptodate/connected until I resume B => panic
Delete on A the shared folder with B and recreated => OK uptodate on A
But on B, when I added a file, I saw B pushing ~400MiB to A (online with no traffic)
Deleted the folder on B : all is nice now, even local=global
BTW, there was something wrong (non blocking) in A conf I did myself : on A side, UPnP is disabled. There was a mismatch in router port-fw and ST non-default port.

**Comment by AudriusButkevicius** [comment]
@calmh any ideas?

**Comment by khinsen** [comment]
I am getting the same panic message ("removed more than added"). Here is my log: 
[panic-20180123-155433.log](https://github.com/syncthing/syncthing/files/1656437/panic-20180123-155433.log). I noticed this today, but I hadn't used the machine (a laptop) for a few days, so I don't really know what event triggered this.

**Comment by imsodin** [comment]
@khinsen Does this happen on every start? Then please run with `STTRACE=model,db` environment variable set - hopefully seeing what's happening up to the panic reveals the problem.

**Comment by khinsen** [comment]
Yes, the panic is reproducible. Here is the extended log: 
[panic-20180123-174412.log](https://github.com/syncthing/syncthing/files/1656807/panic-20180123-174412.log)

**Comment by calmh** [comment]
@khinsen Does this go away if you set `STDBCHECKEVERY=0`? E.g.,

```
$ STDBCHECKEVERY=0 syncthing
```

from the terminal, assuming it's not already running.

**Comment by khinsen** [comment]
No. Same panic.

**Comment by calmh** [comment]
Then I suspect some sort of effect from @imsodin’s various changes, maybe something around the ingored things and then conversion to that, rather than my persistent stuff which would also be a prime suspect.

**Comment by khinsen** [comment]
One more information potentially of interest: I still have an older development build of syncthing on my machine, from doing some testing for another issue. The file is called `syncthing-macosx-amd64-v0.14.43-rc.1+9-g744a5500.tar.gz` and dated Jan 5. I just tried to fire it up again - and I got the same panic. So whatever causes my panics, it's not a recent change to syncthing.

**Comment by imsodin** [comment]
I might have found something that is wrong in meta.go, but I don't see how it can lead to negative counts and it works that way for a long time (since before your persistent meta and my global invalid changes), so I might be wrong:  
Invalid files are not handled at all. That can lead to an incorrect state e.g. like this:
1.  File added --> files++
2. File ignored: nothing happens
3. File is deleted on disk and then unignored: nothing happens on removal of the old invalid file, and deleted++
Result: files++ and deleted++, expected just deleted++. However I can't think of an inverted scenario that brings the counters down.

Also I am confused by the log preceding the panic: The last log line from folder "wwyag-ghhhi" causing the panic shows it is at the end of scanning, walking the db to find deleted files, however the panic is coming from the puller. There are unconditional log statements in between those two events. Is it possible that the logging is delayed compared to the panic?

**Comment by imsodin** [comment]
@calmh Do you have any more ideas about investigations @khinsen could do?

Otherwise the next thing I see to try and solve his particular problem would be to reset the indexes, but that might erase any chance for further debugging.

**Comment by khinsen** [comment]
One more observation that may be of interest: The first time I start Syncthing on my computer after booting, it works fine. If I quit and restart, I get the panic message discussed here. The only way to get back to a functioning Syncthing is rebooting.

**Comment by bugith** [comment]
Even killing the 2 syncthing processus ?

**Comment by khinsen** [comment]
I can't test that anymore. By now syncthing crashes every time, even right after booting.

**Comment by imsodin** [comment]
I can't think of anything in rebooting that should influence Syncthing. Try whether it goes away when running it with `-reset-deltas`.

**Comment by khinsen** [comment]
No, same panic error message.

**Comment by AudriusButkevicius** [comment]
So the env var @calmh gave you is wrong. It doesn't match in the docs versus implementation. Try:
```
STRECHECKDBEVERY=0 syncthing
```

**Comment by khinsen** [comment]
Success - no more panic!

**Comment by calmh** [comment]
Ok then the ball is back in my court
