### ISSUE TITLE
Out of sync when using file system watcher while working with tortoisehg

### ISSUE THREAD

**Issue by alguryanow** [syncthing/syncthing#4914]
If I work with tortoisehg (mercurial) in a folder with capital letters and file system watcher is enabled I get "out of sync"

### Version Information

Syncthing Version: v0.14.47 (and earlier, look bottom)
OS Version: Windows XP SP3
TortoiseHG Version: 
    3.6.3 (Mercurial-3.6.3, Python-2.7.9, PyQt-4.11.3, Qt-4.8.6)  on PC-1
    4.5.2 (Mercurial-4.5.2, Python-2.7.14, PyQt-4.11.4, Qt-4.8.7) on PC-2

### Steps to reproduce
(all is done using web-GUI)

1) On PC-1 create folder "test-sync3" and add it to syncthing with label "test3"; enable file system watching for it and share it with PC-2
2) On PC-2 accept proposal from PC-1 and add this folder
3) On PC-1 create subfolder "FolderWithCapitalLetters"
4) On PC-2 wait for this folder to appear and open it in Windows Explorer
5) On PC-1 enter to "FolderWithCapitalLetters" and create there mercurial repository using Windows Explorer's context menu

At this time you should get 
- on PC-1: 
    - subfolder ".hg" and file ".hgignore"
    - the following messages in syncthing console:

[GE2G4] 08:48:36 INFO: Device N332CVF-LOL3TQO-I3UKCPV-5YZKXQV-FXQ3E2D-EW7NKHE-CN74DGN-4FMMHAA folder "test3" (uvf5m-2drvz) has a new index ID (0x1FEDC20563A11DA0)
[GE2G4] 08:49:23 INFO: Puller (folder "test3" (uvf5m-2drvz), file "FolderWithCapitalLetters\\.hg\\thgstatus"): finisher: file modified but not rescanned; will try again later
[GE2G4] 08:49:23 INFO: Puller (folder "test3" (uvf5m-2drvz), file "FolderWithCapitalLetters\\.hg\\00changelog.i"): finisher: file modified but not rescanned; will try again later
[GE2G4] 08:49:23 INFO: Puller (folder "test3" (uvf5m-2drvz), file "FolderWithCapitalLetters\\.hg\\requires"): finisher: file modified but not rescanned; will try again later
[GE2G4] 08:49:23 INFO: Folder "test3" (uvf5m-2drvz) isn't making progress. Pausing puller for 1m0s.

- on PC-2:
   -subfolder ".hg" and file ".hgignore" (as on PC-1)
   -file "~syncthing~.hgignore.tmp"
   -the following messages in syncthing console:

[N332C] 08:51:45 INFO: Puller (folder "test3" (uvf5m-2drvz), file "folderwithcapitalletters\\.hgignore"): finisher: file modified but not rescanned; will try again later
[N332C] 08:51:46 INFO: Folder "test3" (uvf5m-2drvz) isn't making progress. Pausing puller for 1m0s.
[N332C] 08:51:46 INFO: Puller (folder "test3" (uvf5m-2drvz), file "folderwithcapitalletters\\.hgignore"): finisher: file modified but not rescanned; will try again later
[N332C] 08:51:46 INFO: Folder "test3" (uvf5m-2drvz) isn't making progress. Pausing puller for 1m0s.
[N332C] 08:51:46 INFO: Puller (folder "test3" (uvf5m-2drvz), file "folderwithcapitalletters\\.hgignore"): finisher: file modified but not rescanned; will try again later
[N332C] 08:51:46 INFO: Folder "test3" (uvf5m-2drvz) isn't making progress. Pausing puller for 1m0s.
[N332C] 08:51:46 INFO: Puller (folder "test3" (uvf5m-2drvz), file "folderwithcapitalletters\\.hgignore"): finisher: file modified but not rescanned; will try again later
[N332C] 08:51:46 INFO: Folder "test3" (uvf5m-2drvz) isn't making progress. Pausing puller for 1m0s.
[N332C] 08:51:59 INFO: Puller (folder "test" (UMWuQ-LhYvN), file "folderwithcapitalletters\\.hgignore"): finisher: file modified but not rescanned; will try again later
[N332C] 08:51:59 INFO: Folder "test" (UMWuQ-LhYvN) isn't making progress. Pausing puller for 1m0s.

(Note that "FolderWithCapitalLetters" is writed as "folderwithcapitalletters" - all chars are lowercase.)

   - "Out of Sync" for "test3" in web-GUI

This test was repeated 3 times. Once I've got in syncthing console:

[N332C] 08:42:55 INFO: Puller (folder "test2" (mEnYd-6ik7W), file "FolderWithCapitalLetters\\.hgignore"): finisher: rename \\?\d:\gav\sync-test2\FolderWithCapitalLetters\~syncthing~.hgignore.tmp \\?\d:\gav\sync-test2\FolderWithCapitalLetters\.hgignore: Процесс не может получить доступ к файлу, так как этот файл занят другим процессом.
[N332C] 08:42:55 INFO: Folder "test2" (mEnYd-6ik7W) isn't making progress. Pausing puller for 1m0s.

("Процесс не может получить доступ к файлу, так как этот файл занят другим процессом" is in Russian and means "Process is unable to get access to the file because it is open by another process".)
And I still got the file "~syncthing~.hgignore.tmp" on PC-2 but not "Out of Sync".

There is no such problems when file system watching is not enabled.

It's not an issue of 0.14.47 - I've got same problems before, with syncthing-inotify. But right now I have prepared the steps to reproduce the problem.

**Comment by calmh** [comment]
So the thing here is that previously you could have a folder which on disk is called `FOO` and tell Syncthing about it as `foo`. We would use `foo` and never know better. Now, however the fs notification thing will tell us about `FOO` and confusion ensues.

We fixed something related to this, but maybe not all. @imsodin, ideas?

**Comment by calmh** [comment]
If there's a directory "FOO" on disk, you can tell Syncthing to look at "foo". This mostly works, because the filesystem is case insensitive. But since it's the filesystem that generates notifications, when something changes it will tell Syncthing about the change inside "FOO". Syncthing doesn't know what to do with this since that's not the folder name it knows.

Syncthing should be case insensitive, but isn't.

The workaround in this case is to remove the folder and create it again, making sure the name given to Syncthing is the same as that on disk, exactly.

**Comment by AudriusButkevicius** [comment]
It does not assume foo, there was FOO at some point which is now causing confusion. From windows perspective its the same directory, as windows it's not case sensitive. From syncthings perspective it's two different directories.

The workaround is to rename the directory to something completely different, rescan and rename it back to whatever case you want.

**Comment by alguryanow** [comment]
Sorry, I still do not understand. Who changes the name from "FOO" to "foo"? I don't tell syncthing anything about "FOO" or "foo" - I just create a folder "FOO" deep inside in subtree of a folder that I want to share between my computers:
- I create folder "shared-folder" and ask syncthing to synchronize them (add them to syncthing using web-GUI)
- I accept the proposal on second computer and create "shared-folder" on them
- then I forgot about syncthing (from this moment I do not interract with syncthing directly) and just work inside "shared-folder": 
        - create subfolder "FOO" (and it is successfully created on second computer as "FOO")
        - and make a mercurial-repository inside them.  
Where do the name "foo" come from? From a file system notification?

What means "making sure the name given to Syncthing is the same as that on disk, exactly" in this situation?

**Comment by alguryanow** [comment]
2018-05-03 10:26 GMT+03:00 Audrius Butkevicius <notifications@github.com>:

> It does not assume foo, there was FOO at some point
>

it is still there: in Windows Explorer I still see "FOO", not "foo"


> which is now causing confusion. From windows perspective its the same
> directory, as windows it's not case sensitive. From syncthings perspective
> it's two different directories.
>
this is understandable. I do not understand who and when changes the name
from "FOO" to "foo" and back (it's changes back to "FOO", because Windows
Explorer shows me "FOO"). Right now it seems to me that a file system
watcher notifies syncthing about "foo" and not about "FOO".


> The workaround is to rename the directory to something completely
> different,
>
on what computer: on PC-1 (where I work) or on PC-2 (where changes should
be synced to) ?


> rescan and rename it back to whatever case you want.
>
Hmmm... it seems that I have to repeat that each time I do something with
tortoisehg...

**Comment by calmh** [comment]
So this goes back to general case sensitivity issues, #2739 etc
