### ISSUE TITLE
Syncing issues, database missing sequence entries

### ISSUE THREAD

**Issue by midnightdim** [syncthing/syncthing#6304]
I recently installed and configured Syncthing to sync files across multiple devices. It seemed to work on some folders, but then I ran into an issue or maybe even 2 different issues.

There's one folder X shared from device A (Home PC) to device B (Brix).
The current issue is:
1. Device B shows (in syncthing UI) that it's "Up to Date" with device A.
2. Device B shows local state different from global state for the folder X. Both device A and device B show the same global state (which is expected).
3. Device A shows "syncing" with device B, but nothing really happens.
4. Device A shows some "Out of Sync Items" - I randomly checked 4-5 files on device B - they exist there. But the total folder sizes are different on device A and device B (the latter is smaller).

Device A:
![изображение](https://user-images.githubusercontent.com/6467552/73632212-a4f3de00-468d-11ea-982e-61bc24038bca.png)
![изображение](https://user-images.githubusercontent.com/6467552/73632244-b4732700-468d-11ea-9423-5d98c01af8a1.png)

Device B:
![изображение](https://user-images.githubusercontent.com/6467552/73632260-c2c14300-468d-11ea-8a61-ae536969d743.png)
![изображение](https://user-images.githubusercontent.com/6467552/73632275-ce146e80-468d-11ea-9e41-c76a373087d5.png)

--

There's another folder Y also shared from device A to device B.
The problem is:
1. The total size of this folder on the file system is different on A and B. On device B the size is smaller. [UPDATE: this was incorrect - see my comment below]
2. In syncthing UI device A and device B show different number of files for this folder (and different total size) - that's unexpected, and each of them shows that local state is equal to global state. Also, the total size and files count shown on device B are bigger than what device A shows - this is unexpected since all files came to B from A and also wrong (see point 1).

Device A:
![изображение](https://user-images.githubusercontent.com/6467552/73632164-9279a480-468d-11ea-8d84-430b14ed4cdc.png)

Device B:
![изображение](https://user-images.githubusercontent.com/6467552/73632144-85f54c00-468d-11ea-9e84-47f4aa4ddbb8.png)

--

In the logs I don't see any issues. Tried restarting syncthing on both ends, even reinstalled it on device A, the problems are still there.

Version Information:

Device A:
syncthing v1.3.3 "Fermium Flea" (go1.13.4 windows-amd64) teamcity@build.syncthing.net 2019-12-08 12:31:26 UTC
OS Version: Windows 7

Device B:
syncthing v1.3.3 "Fermium Flea" (go1.13.4 linux-amd64) deb@build.syncthing.net 2019-12-08 12:31:26 UTC
OS Version: Debian 10

**Comment by calmh** [comment]
I suspect you are suffering from db inconsistencies for some reasons, one possibility being the one fixed in #6239 recently. Unfortunately that fix isn't out in any release yet and won't be for about a week (1.4.0-rc.1 on the 11th). If you're willing, I'd like to look at the databases in question ("index-0.14.0.db" in the config dirs), especially given the last folder which is "in sync" yet mismatching. If you could zip those up and put them somewhere on the internet, privately if you like (my email is  in my profile and ... everywhere).

**Comment by midnightdim** [comment]
Thanks, I will consider this.
In the meantime I attempted to manually "fix" the problem by moving the files (mentioned in the out of sync list) on device A out of the folder and back. This triggered re-sync and now device A shows that it's "Up to Date" with device B.

However, the folder X still has different sizes on the devices. And I still see this.

Device A:
![изображение](https://user-images.githubusercontent.com/6467552/73633660-d1115e00-4691-11ea-9b71-26eba245b854.png)

Device B:
![изображение](https://user-images.githubusercontent.com/6467552/73633676-de2e4d00-4691-11ea-8b57-2224f7f8421c.png)

**Comment by midnightdim** [comment]
> I'd like to look at the databases in question ("index-0.14.0.db" in the config dirs), especially given the last folder which is "in sync" yet mismatching. If you could zip those up and put them somewhere on the internet, privately if you like (my email is in my profile and ... everywhere).

Sent via email. Thank you.

**Comment by calmh** [comment]
Thanks for the indexes. Looking at those there's a systematic problem of missing sequence entries. 

A (Windows):

```
% stindex -mode idxck index-v0.14.0.db.windows
Sequence entry missing for FileInfo "....", folder "jxxmg-demss", seq 2794
...
Folder 6 missing 15 sequence entries: #2790 - #2804
Folder 6 missing 2 sequence entries: #2806 - #2807
Folder 6 missing 4 sequence entries: #2812 - #2815
Folder 6 missing 2 sequence entries: #2819 - #2820
```

The entries in this case are for folders.

B (Linux):

```
Sequence entry missing for FileInfo "..., folder "qp3zu-wkpkj", seq 76
Folder 6 missing 15 sequence entries: #2790 - #2804
Folder 6 missing 2 sequence entries: #2806 - #2807
Folder 6 missing 4 sequence entries: #2812 - #2815
Folder 6 missing 2 sequence entries: #2819 - #2820
```

The entries are for normal files (non-deleted, non-invalid, etc.) that each look fine.

So something is causing us to either not flush sequence entries to disk or the database forgets them after the fact. This needs looking at.

**Comment by calmh** [comment]
Frankly I don't see how this could happen without the bug being somewhere in the database I/O itself. When updating files we iterate over the files, and for each file write the new entries and sequences and potentially flush the batch to disk. It's not like we first write the file entries in a batch and only then the sequences. The only thing that sets the sequences apart from the other entries is that they have a higher prefix so when compacted they all get stuffed into a higher numbered file than the file entries...

**Comment by midnightdim** [comment]
I am happy to do more testing and/or provide more information if needed.
My only observation so far is that the issues happened on relatively big folders with thousands of files.

Not sure if this helps, but also:
1. After adding the folder X and starting the sync I noticed that some files are unnecessary and deleted them from device A during  the sync. I guess this is a normal situation, but still I kind of interfered.
2. I also noticed another minor bug with another folder that I synced with my phone. So on the phone I enabled sync with devices A and B and then in web UI of both A and B I checked this folder to be shared between these devices. Later, when I ran into the issues described above I thought that it could be somehow related (because device A also showed these files in the "out of sync" list), so I decided to uncheck the sync of this folder between devices A and B. However, after I unchecked it and clicked "Save" I noticed that the files were still in that list, and when I reopened the sharing dialog for that folder on A or B (don't remember exactly) it was still on like if I haven't disabled it. I repeated that a number of times until it finally got disabled and the files disappeared from "out of sync" list.
This is most likely unrelated, but I'm just reporting as much as I can :-)

**Comment by calmh** [comment]
I suspect unrelated on both counts. Trying reproduce via stress test but no luck on that so far unfortunately.

**Comment by midnightdim** [comment]
So the problem continues.
With folder X I decided to re-share it with another remote device C, which already has this folder in a more up-to-date state (I synced it before with device A using Resilio).
My overall goal was to keep devices A and C in sync using B as a kind of a proxy.
So I had to delete folder X from A and B in Syncthing UI (otherwise it created duplicate folder - I'm not sure how this should be managed in Syncthing - if I already have a folder on A and B in sync and C has the more recent version of this folder - how do I put them all in sync?).
Then I shared this folder from device C with both A and B.

The results are:
1. Some re-sanning happened on A and B.
2. Nothing seems to have changed in terms of the files on A and B - they are not synced with C and also still out of sync with each other. And nothing is syncing.
3. C currently shows it's syncing with A and B - both in "Folders" and "Remote Devices" sections.
4. A and B currently show the folder as "Up to Date", but in "Remote Devices" they show "syncing" with C.

Is there some workaround to fix this? I really wanted to switch to Syncthing and I'm okay to do some manual fixes, but I need this data in sync to keep working on my projects.

**Comment by midnightdim** [comment]
Regarding different sizes of folders - I think I found the reason.
The thing is - on Debian I was checking the size in Midnight Commander (mc), and it seems that it has some inconsistency in its size calculations. Will double check that.

**Comment by midnightdim** [comment]
Sorry for these chaotic updates - as mentioned, I have to get these files in sync. So I just synced them between A and C with Resilio and re-ran Syncthing.
Although all files were in sync and total size of the folders was the same Syncthing showed some files as "out of sync" on device C. So I just deleted them manually on C and re-ran the sync and finally got Syncthing to understand that this folder was in sync on A and C.
Weird.

**Comment by imsodin** [comment]
While there's no mentioning of crashes/panics/unclean shutdowns in the comments, the missing indexes still make it likely that the underlying problem is https://github.com/syncthing/syncthing/issues/6335, which has been fixed (but not yet released). Please report if you still experience this with >= 1.4.0-rc.5.

**Comment by calmh** [comment]
Yep!

**Comment by eprigorodov** [comment]
After upgrading syncthing to the fixed version the problem might still persist and then can be finally fixed by running `syncthing -reset-database`.
